### ISSUE TITLE
Update saveJSON to return serialized data

### ISSUE THREAD

**Issue by HieronymusLex** [iVis-at-Bilkent/cytoscape.js-expand-collapse#140]
Currently the `saveJSON` returns nothing and always writes to file, however there are use cases where one would want the contents of what `saveJSON` is writing, without actually writing it to a file (e.g. in order to pass the data to an API call).

Could we have `saveJSON`:

1. Conditionally write to file
2. Return the stringified data that is being written

Alternatively, this could be surfaced via a new method?

**Comment by hasanbalci** [comment]
I think you're right. We will look into that.

**Comment by hasanbalci** [comment]
Now, `saveJSON` always returns the stringified data and writes to a file only if `filename` parameter is provided. If not, it doesn't write to a file. The change is done in the *unstable* branch and will also be active in the master branch when we merge it before a release. @HieronymusLex, can you please verify and close the issue if it is ok?

**Comment by HieronymusLex** [comment]
@hasanbalci seems to be working - thanks! One issue I'm running into is if I:
1. collapse a node
2. store the result of `saveJson` then refresh the page, and pass the previously stored result to `loadJson`
3. try to expand the collapsed node 
 
only the collapsed children appear correctly, not the "collapsed edges". The console displays an error saying:

```
expandCollapseUtilities.js:622 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at Object.findNewEnd (expandCollapseUtilities.js:622:1)
    at Object.repairEdges (expandCollapseUtilities.js:638:1)
```

which is caused by `parent` being undefined at `parent = parentData[parent.id()];`

Pseudo code for reference:

```
const data = canvas.expandCollapse('get').saveJson()
// store data....refresh... get data
const api = canvas.expandCollapse('get')
api.loadJson(data)
```

Any ideas what could be happening here?

**Comment by Nicolas-PredictaLab** [comment]
So it never reach the master branch, right ? :D

**Comment by ugurdogrusoz** [comment]
@Nicolas-PredictaLab We are currently working on a unified complexity management framework, so this one is not maintained. Sorry.

**Comment by svozza** [comment]
Can we put an indication in the README that this library is not maintained, just so people know for when they start new projects to use use something else?

**Comment by ugurdogrusoz** [comment]
> Can we put an indication in the README that this library is not maintained, just so people know for when they start new projects to use use something else?

Done

**Comment by ugurdogrusoz** [comment]
Bu otomatik mi kapanmış geri mi açmak lazım ?On Aug 28, 2024, at 6:20 PM, Hasan Balcı ***@***.***> wrote:﻿
Closed #140 as completed via 2158ae4.
